# Generated by Django 2.2.3 on 2019-11-19 05:54

from django.db import migrations, models
import ration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familydb',
            fields=[
                ('aadhaar', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=12)),
                ('age', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feedbackdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ee', models.CharField(max_length=100)),
                ('complain', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='logindb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationcardno', models.CharField(max_length=4)),
                ('licenseno', models.CharField(max_length=4)),
                ('emailidd', models.CharField(max_length=100)),
                ('passwordd', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='pricebpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar', models.CharField(max_length=100)),
                ('oil', models.CharField(max_length=100)),
                ('corn', models.CharField(max_length=100)),
                ('wheat', models.CharField(max_length=100)),
                ('rice', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=100)),
                ('dal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pricedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100, validators=[ration.models.pricedb.sa])),
                ('sugar', models.CharField(max_length=100)),
                ('oil', models.CharField(max_length=100)),
                ('corn', models.CharField(max_length=100)),
                ('wheat', models.CharField(max_length=100)),
                ('rice', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=100)),
                ('dal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rationdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadharnoo', models.CharField(max_length=100)),
                ('datee', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=4)),
                ('serial', models.CharField(max_length=10)),
                ('product', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('bill', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=100)),
                ('rationn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='registerdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userselection', models.CharField(max_length=100)),
                ('rationbooktype', models.CharField(max_length=100)),
                ('sel', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=100)),
                ('shopno', models.CharField(max_length=100)),
                ('shopaddress', models.CharField(max_length=100)),
                ('aadharcard', models.CharField(max_length=100)),
                ('passbook', models.CharField(max_length=100)),
                ('income', models.CharField(max_length=100)),
                ('residential', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('gas', models.CharField(max_length=100)),
                ('electricity', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=8)),
                ('credential', models.CharField(max_length=100)),
            ],
        ),
    ]
