# Generated by Django 2.2.3 on 2019-11-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0002_auto_20191123_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationdb',
            name='otp',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
