# Generated by Django 2.2.3 on 2019-12-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0003_rationdb_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationdb',
            name='ration_key',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
