# Generated by Django 2.2.3 on 2019-12-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0004_auto_20191207_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdb',
            name='complain',
            field=models.CharField(max_length=500),
        ),
    ]
