# Generated by Django 3.0.5 on 2020-04-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0005_auto_20191209_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='tokondb',
            fields=[
                ('ration_key', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=10)),
                ('product', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
            ],
        ),
    ]
